### ISSUE TITLE
Black Screen @ http://localhost:8080/

### ISSUE THREAD

**Issue by Raj123456788** [eduardomota/ffmpeg-stream#1] opened 2020-12-12 00:44 UTC
Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
Invalid file index 1 in filtergraph description [0:v]scale=1280:720,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=1280:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=1280:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error

**Comment by supermarsx** [comment] 2020-12-12 12:48
Hi, please try and change filter scales to match video scale like this,
your stream scale is 240x160
but the filter is "1280:720" in "filtergraph description [0:v]scale=1280:720,fifo[scaled];" it should be replaced with "240:160" it should as well change the other to instances of "scale=1280" from "1280" to "240".

Scale of filters, images and other assets should always match across the setup, the default logo may be too big for that stream resolution, you may also change that to adapt it further.

Cheers

**Comment by Raj123456788** [comment] 2020-12-14 19:18
Hello,
still getting the error
Input #0, rtsp, from 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov':
  Metadata:
    title           : BigBuckBunny_115k.mov
  Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
Invalid file index 1 in filtergraph description [0:v]scale=240:160,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=240:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=240:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error


This is what I changed to:
    '-filter_complex': "[0:v]scale=240:160,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=240:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=240:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25", // Complex filtergraph, overlays, etc


My source is rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov . & I am running on windows machine.

**Comment by Raj123456788** [comment] 2020-12-14 20:07
![download](https://user-images.githubusercontent.com/16295521/102129784-cae92380-3e04-11eb-955f-809725413d4a.png)
Can you please throw some light as to how to determine the default logo? The stream works with VLC but this is what i see on the webpage. Waiting for your answer.

**Comment by Raj123456788** [comment] 2020-12-15 17:10
Hello,
Can you please answer if possible. Thanks!

**Comment by Raj123456788** [comment] 2020-12-15 20:16
Getting below error for my rtsp stream and are there any changes required to be done for the local host?
  Program 1
    Stream #0:1: Video: h264 (Constrained Baseline) (HDMV / 0x564D4448), yuv420p(progressive), 1280x720, 240 tbr, 90k tbn
    Stream #0:0(en): Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
Invalid file index 1 in filtergraph description [0:v]scale=1280:720,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=1280:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=1280:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error

**Comment by supermarsx** [comment] 2020-12-15 23:09
Hi again Raj

My precise configuration on how to do the stream and using the logo goes like this

1. Clone this project
2. Install dependencies through npm
3. Cd into the server folder on CMD as it follows
![image](https://user-images.githubusercontent.com/17675589/102283164-bc485c80-3f29-11eb-946c-f3e63f8ea5f6.png)
4. Execute "node stream-client.js"
![image](https://user-images.githubusercontent.com/17675589/102283338-27922e80-3f2a-11eb-8e95-d9c6490b169c.png)
5. Execute "node stream-server.js"
![image](https://user-images.githubusercontent.com/17675589/102283256-f4e83600-3f29-11eb-96c5-886f97162773.png)
6. Open chrome (or other suitable browser) and navigate to http://localhost:8080/
![image](https://user-images.githubusercontent.com/17675589/102283535-89529880-3f2a-11eb-8d91-3894e4c25c78.png)

With this it should work as intended with an exact clone of the repository.

**Comment by Raj123456788** [comment] 2020-12-15 23:23
Duration: N/A, start: 3600.051244, bitrate: N/A
  Program 1
    Stream #0:1: Video: h264 (Constrained Baseline) (HDMV / 0x564D4448), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 90k Hello  there, just tried with my rtsp link still does not work!
    Stream #0:0(en): Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
Invalid file index 1 in filtergraph description [0:v]scale=1280:720,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=1280:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=1280:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error

**Comment by Raj123456788** [comment] 2020-12-15 23:27
Hi, Did you make any changes to stream-server.js. I think it is different than what is uploaded on github since it has 1280x720.

My FFMPEG version:
ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805

Here is the output after changing 240x160
ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.101 / 58.101.101
  libavformat    58. 51.101 / 58. 51.101
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, rtsp, from 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov':
  Metadata:
    title           : BigBuckBunny_115k.mov
  Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
Invalid file index 1 in filtergraph description [0:v]scale=240:160,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=240:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=240:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error

**Comment by supermarsx** [comment] 2020-12-16 00:03
> Hi, What OS are you using? Iam using windows! Did you make any changes to stream-server.js. I think it is different than what is uploaded on github since it has 1280x720

There are no changes to the file whatsoever, the scale should be alright even though the stream has a different one, its a matter of scale, the original OS is Win 10 1803, ffmpeg 3.4, npm up to date. Please make sure you're using the same ffmpeg version. I'll troubleshoot potential scenarios better at another time. The issue you're facing is that FFMPEG is not liking the file input "aka RTSP" stream, this means that theres either an issue with the command itself of ffmpeg, i don't know which because i haven't done any deeper debug. If you want to look it yourself you may want to start by looking here
https://ffmpeg.org/ffmpeg.html
I hope that this has been somewhat useful.

My best guess is that the input you're getting for the first parameter is Audio when it should be the video that meaning that you would need to target the video stream instead.

**Comment by Raj123456788** [comment] 2020-12-16 00:13
how can I target only video stream? For Same FFMPEG version I am getting below error

stream: New WebSocket Connection (1 total)
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[udp @ 0000020c8013e0a0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 0000020c81a531a0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 0000020c8013ede0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 0000020c8013eea0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
Input #0, rtsp, from 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov':
  Metadata:
    title           : BigBuckBunny_115k.mov
  Duration: 00:09:56.48, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 12000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, 24 fps, 24 tbr, 90k tbn, 48 tbc
Invalid file index 1 in filtergraph description [0:v]scale=240:160,fifo[scaled]; [1:v]scale=100:-1[logo]; [2:v]scale=240:-1,fifo[mask]; [scaled][mask]alphamerge,hue=s=0[pmask]; [pmask]boxblur=1[masked]; [0:v]scale=240:-1,fifo[bg]; [bg][masked]overlay=format=auto[video]; [video][logo]overlay=25:25.
RTSP stream exited with error

**Comment by supermarsx** [comment] 2020-12-16 13:25
There was a fundamental error on the parameters passed to ffmpeg within the library that i've corrected locally but didn't update on github, i'll be pushing the fix later.

This was because node_modules don't get committed to github..

**Comment by Raj123456788** [comment] 2020-12-16 17:51
Thank you so much for the update. I would appreciate if you explain either a block diagram or few lines of explanation. I am trying to understand node-rtsp-stream.

**Comment by supermarsx** [comment] 2020-12-16 18:09
'node-rtsp-stream' is kind of broken, the reason why it didn't work out of the box with the needed parameters.

Basically 'node-rtsp-stream' forwards your parameters to ffmpeg and platforms it to a new stream in an easy way right from node.
ffmpeg is a multipurpose tool to convert video, on-the-fly, etc. I've put a mask.png file that with the filtergraph allows you to blur parts of the screen by painting it white on mask.png file. Don't mind much about that if you're not looking forward to read a good part of ffmpeg's documentation and playing with sockets which may be daunting for new comers.

As it stands it works like this
(stream-server.js)
RTSP Stream ==> ffmpeg (filter, scale, add logo, blur, etc.) ==> Node web socket <==> Client socket connection
(stream-client.js)
Express server (embeds the stream connection on html) <==> Client connection

I'm closing this. Cheers

**Closed as completed by supermarsx** 2020-12-16 18:09 UTC

**Comment by Raj123456788** [comment] 2020-12-16 18:34
It works. Once again Thank you for the help!

**Comment by Raj123456788** [comment] 2020-12-16 19:03
Sorry to bother again: for my rtsp stream I am getting chopped image as below. where can I set the parameters for this:
![image](https://user-images.githubusercontent.com/16295521/102394015-fe0aee80-3f8d-11eb-85b3-f0f84787ce81.png)

**Comment by Raj123456788** [comment] 2020-12-16 19:08
Never mind figured it out. Thanks!

**Comment by supermarsx** [comment] 2020-12-16 20:22
> Sorry to bother again: for my rtsp stream I am getting chopped image as below. where can I set the parameters for this:
> ![image](https://user-images.githubusercontent.com/16295521/102394015-fe0aee80-3f8d-11eb-85b3-f0f84787ce81.png)

For future reference, configuration on this you should refer to ffmpegOptions object inside
https://github.com/eduardomota/ffmpeg-stream/blob/master/server/stream-server.js
to further refine the options you should refer to ffmpeg documentation on the command line parameters

Thank you
